spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/db?useSSL=false
    username: user
    password: user
    kafka:
      consumer:
        auto-offset-reset: earliest
  cloud:
    consul:
      host: docker.host.internal
      port: 8500
      discovery:
        service-name: credit-api
        instance-id: credit-api
    config:
      enabled: false
kafka:
  bootstrap: http://localhost:9092
  topic:
    payed: CREDIT_PAYED
    check: CREDIT_CHECK
credit:
  penalty:
    amount: 50
    warn: 0.3
    collector: 0.5
    days: 1
logger:
  default: com.frizzer.logger
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
        r2dbc: DEBUG
server:
  port: 7003
reactive-feign:
  client:
    client-api:
      url: http://localhost:8000/client
