spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/db?useSSL=false
    username: user
    password: user
  kafka:
    consumer:
      auto-offset-reset: earliest
  cloud:
    config:
      enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: payment-api
        instance-id: payment-api
kafka:
  bootstrap: http://localhost:9092
  topic:
    payment: CREDIT_PAYMENT
server:
  port: 7002
logger:
  default: com.frizzer.logger
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
reactive-feign:
  client:
    credit-api:
      url: http://localhost:8000/credit


