spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
  cloud:
    config:
      enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: notification-api
        instance-id: notification-api
logger:
  default: com.frizzer.logger
kafka:
  bootstrap: http://localhost:9092
  group:
    id: creditConsumers
  topic:
    check: CREDIT_CHECK
    payed: CREDIT_PAYED
    payment: CREDIT_PAYMENT
server:
  port: 7001

